lib/bcoin/txdb.js

broke for me while playing around with the spvnode. `removeBlockSPV` => `getHeightHashes` => `getHeightRangeHashes`

fix args normalization in getHeightRangeHashes

---

lib/bcoin/utils.js

- Calling process.hrtime is predicated on being called with an Array type with two elements or with no explicit parameters.
- Node 4 (LTS) seems to be persnickety regarding matching undefined as a
actual parameter in process.hrtime (and possibly all functions).

Node 4 process.hrtime(undefined)

---

test/hd-test.js

- Tests derivation implementation to bip32 spec when private key has leading zeros as it's possible that the private key could be represented with less than 32 bytes, but should use full 32 bytes.
- Cross tested against:
- libbtc at https://github.com/braydonf/libbtc/commits/cross-ref
- hdkey at https://github.com/cryptocoinjs/hdkey/pull/9
- yours-bitcoin at https://github.com/yoursnetwork/yours-bitcoin/pull/48
- bitcoinjs-lib at https://github.com/bitcoinjs/bitcoinjs-lib/pull/673
- bitcore-lib at https://github.com/bitpay/bitcore-lib/pull/97

test: include derivation test when private key has leading zeros

---

lib/primitives/mtx.js

Changed public key comparison at mtx.js signVector method for P2PK case. Before It gave an error while using an imported raw coinbase transaction. I don't know if the same change is needed for the other comparison cases.

Solved p2pk ownership comparison in mtx

---

bin/cli
lib/chain/chain.js
lib/chain/chaindb.js
lib/hd/mnemonic.js
lib/hd/private.js
lib/hd/public.js
lib/http/client.js
lib/http/rpc.js
lib/http/server.js
lib/http/wallet.js
lib/net/peer.js
lib/node/config.js
lib/node/fullnode.js
lib/node/spvnode.js
lib/wallet/account.js
lib/wallet/browser.js
lib/wallet/masterkey.js
lib/wallet/records.js
lib/wallet/txdb.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
lib/wallet/walletkey.js
migrate/walletdb5to6.js
test/chain-test.js
test/http-test.js
test/wallet-test.js

Features:
- Better chain syncing. Maintains a start block to avoid rolling back to the genesis block for rescans. Looks for a block in the main chain on boot to handle crashes during reorgs instead of rescanning back 36 blocks.
- Outpoint maps - necessary for any block scanner that has no access to the coin addresses.
- Block records - each wallet will record every txid of theirs that made it into a block. Exposed on the api `$ bcoin wallet blocks` and `$ bcoin wallet block [height]`.
- Account address indexing - faster address by account iteration.
- Account index->name indexing - faster account name lookups for tx details.
- A `client` object is now passed in to resemble an API client once we separate the walletdb from the node.
Migration is in `migrate/walletdb5to6.js`. Requires a …

WalletDB v6

---

lib/utils/bloom.js

When constructing a bloom filter from number of items and a rate, if the number of items is too large the value of n was coming to zero. The minimum value of n should be 1, otherwise the bloom filter doesn't function correctly.
This was the case in spv mode where the walletdb was creating a bloom filter for 1million items:
`Bloom.fromRate(1000000, 0.001, 1);`

bloom: fix minimum value of n

---

lib/primitives/netaddress.js

When a `pool` is created with spv enabled, the BLOOM service flag is set on `pool.needed` value.
This is resulting in no host passing the `addr.hasServices(this.needed)` test in `pool.getHost()` and as a result no hosts to connect to.
Fix: setting the BLOOM flag on the address `services` property when adding the host to the hostlist.

netaddress: fix fromHost to include BLOOM service

---

lib/node/spvnode.js

Broken here: https://github.com/bcoin-org/bcoin/commit/199699d7#diff-b00afaadd4f3e1b8c0f56c2f988566fdL172
Just need to remove the underscores.

spvnode: fix incorrect function call.

---

lib/net/pool.js

When the pool disconnects, it destroys the peers list. As peers get destroyed when the underlying sockets are closed, pool.handleClose is invoked as the event handler for the peer 'close' event, which tries to remove the peer from the peers list again. Since it was destroyed this is resulting in [failed assert here](https://github.com/bcoin-org/bcoin/blob/bae2aa33ddba7092ca1bf8f205937218bdc29d41/lib/net/pool.js#L3681).
This fix ensures we stop processing all events from a peer if it is forcefully destroyed during pool shutdown, and resets the nonces and peers.list, to gracefully shutdown and disconnect the pool.
Calling pool.connect() again after shutdown tested to work correctly.
All unit tests are passing.

pool: graceful disconnect

---

lib/wallet/wallet.js

It may be undesirable in some applications to automatically sort inputs and outputs when constructing a transaction. 
In this PR changing behaviour so `Wallet.createTX` will skip sorting if `noSorting` is set in options.
Default behaviour is unchanged, bip69 sorting is still applied.
To disable bip69 when calling `Wallet.send`
```
Wallet.send({
noSorting: true,
outputs: [ ... ]
})
```

add option to disable bip69 in Wallet.send

---

lib/http/base.js

Typo with DELETE requests looking for DEL keyword. Easy fix.
(Probably should add test cases to cover, but I didn't bother)

HTTP: Fix DELETE requests

---

lib/http/server.js

When I try to make a cross-origin request to the REST API when an API token is set (i.e. when I am connecting using basic auth), I get an error: 
> Fetch API cannot load http://localhost:8334/. Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
Unless this is the intended behavior, I think this can be solved by changing the headers of the response, as shown.

http: add Authorization to allowed headers

---

package.json

Updated socket.io and socket.io-client since the previous versions were dependent on modules with security vulnerabilities.
Those are the vulnerabilities according to a scan using NSP (https://github.com/nodesecurity/nsp)
│ DoS due to excessively large websocket message
│ Name          : ws
│ Installed     : 1.1.0
│ Vulnerable    : <=1.1.0
│ Patched       : >=1.1.1
│ Path          : bcoin@1.0.0-beta.12 > socket.io@1.4.8 > engine.io@1.6.11 > ws@1.1.0
│ More Info     : https://nodesecurity.io/advisories/120
│ Regular Expression Denial of Service
│ Name          : negotiator
│ Installed     : 0.4.9
│ Vulnerable    : <= 0.6.0
│ Patched       : >= 0.6.1
│ Path          : bcoin@1.0.0-beta.12 > socket.io@1.4.8 > engine.io@1.6.11 > accepts@1.1.4 > negotiator@0.4.9
│ More Info     : …

Updated packages with known security issues

---

lib/http/rpc.js
lib/primitives/block.js

Lots of exciting messages in the coinbase string these days! Getting this string currently requires a separate call for `getTransaction()`, and that won't even work (in Core anyway, not sure about bcoin) unless you have `txindex=1`.  I'm currently using the `bcoin rpc getblock ...` for this purpose and it's nice to have it as part of the return array. I haven't been able to test the `bcoin cli block ...` yet because of issue https://github.com/bcoin-org/bcoin/issues/208

return coinbase scriptSig string in getblock requests 

---

lib/btc/amount.js
lib/utils/util.js

I thought this was going to be a simple fix after noticing the call to `parseFloat()` included an un-needed radix parameter (note that unlike `parseInt`, `parseFloat()` does not take a radix parameter). But after a bit of investigation I found that things were a little more nuanced.
(This started from an alert on lgtm here: https://lgtm.com/projects/g/bcoin-org/bcoin/snapshot/d074af8a28d105c4544053bb19cac83ae6438b29/files/lib/btc/amount.js#L491)
I was intending to replace calls to `util.isFloat()` with conversions using `parseFloat()` and checking if the result was `NaN` (given that we need to parse the value anyway), however I discovered that node's implementation of `parseFloat()` is not very strict, and in particular parses strings like `'1.2.3'` as `1.2`. So that would change …

Various improvements to float parsing

---

lib/mempool/mempool.js

This option was not imported but expected in the following lines:
https://github.com/bcoin-org/bcoin/blob/master/lib/mempool/mempool.js#L133
https://github.com/bcoin-org/bcoin/blob/master/lib/mempool/mempool.js#L1831

mempool: import indexAddress option.

---

lib/utils/validator.js
test/http-test.js
test/utils-test.js

- RPC method param semantics, unfortunately, aren't consistent in bitcoin core, therefore bcoin can't be used as a drop in replacement if bcoin "fixes the glitch".
- To avoid breaking bcoin's current api, validation of bool includes integers 0 and 1 as false and true, respectively.
- The effect of this is to allow getRawTransaction to work with older client code.

RPC method compatibility with bitcoin core.

---

README.md

After npm installing, running the command bcoin didn't work. It should be bin/bcoin instead
Michaels-MacBook-Pro:bcoin michaelfolkson$ pwd
/Users/michaelfolkson/bcoin
Michaels-MacBook-Pro:bcoin michaelfolkson$ bcoin
-bash: bcoin: command not found

Add path to bcoin command

---

snap/snapcraft.yaml

This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the Ubuntu store.

Add the packaging metadata to build the bcoin snap

---

package.json

Async/await support comes by default in node version 7.6.0 so using earlier 7 versions fails to run bin/node.

Update node engine requirement to >=7.6.0

---

lib/http/base.js
lib/net/tcp.js

The callback provided to `listen` method on a tcp server (created with `net.createServer` and `http.createServer`)  is only called on success. 
So the promise returned was not correctly being rejected on error (eg. address/port in use). So it was only possible to "catch" this error in the 'error' events, when opening a node or connecting the network pool.
This PR is a simple fix that does the trick.

net/http: correctly reject promise return by listen()

---

lib/net/pool.js

If you configure `bip150` to false, it still checks whether `bip151` is true.

Fix Pool bip150 assert

---

lib/mining/miner.js

Workers option wasn't assigned to the miner(and to CPUMiner)
if you ran mining it would block even with workers.

Worker Options in Miner

---

lib/http/client.js
lib/http/server.js

Rest API for getting Coins by address(es) wasn't working.
getTxByAddress was accepting `address` on post. Changed `addresses` as in coins. (POST request on /coin/address, and /tx/address accepts multiple addresses)

REST API fixes

---

lib/http/client.js

Before, if no id is passed then a wallet with an id of "null" was created. This throws an assertion error before sending the request.

check in http client that an id is passed to create wallet

---

bin/cli
lib/utils/util.js
test/utils-test.js

`bcoin cli tx $address` wouldn't accept bech32 addresses.
It affects only two commands: getTX and getCoin

CLI to accept bech32 addresses

---

bin/cli

Fixes a bug with `cli wallet create` where if no value is specified for the `--watch` option, the `accountKey` is assigned a value of `"true"` which is invalid and causes errors downstream. This fix leaves `accountKey` as `null`, and the resulting functionality appears to match wallet creation via HTTP request where `watchOnly` is true and `accountKey` is not given a value.
This addresses #285.

Allow --watch without accountKey value for cli createWallet

---

lib/http/client.js
lib/http/rpcclient.js

When you receive error from the API, you would always see `Status Code: Number`.
If `body.error` is present, we should return it first and only after that check status code.

Fix bcoin.http.Client errors

---

lib/http/server.js
lib/primitives/block.js
lib/primitives/txmeta.js

Adds a `confirmations` property to the JSON returned by `cli tx [hash]` and `cli block [hash/height]` as
well as the REST `/tx/:hash` and `/block/:block` calls by subtracting TX/block height from chain height.
I'm new to this codebase but I tried to implement this as cleanly and sensibly as I could. It passed all mocha tests as well as some manual testing with regtest.
This addresses issue #320.

Adding confirmations property to block and tx getJSON

---

lib/http/wallet.js

Since outputs are expected to be in the options argument

remove outputs from function signature

---

docs/Configuration.md

Update options related to workers, i.e. `use-workers` renamed to `workers` and `max-workers` renamed to `workers-size`to match the configuration used in the code.

Docs: update worker options

---

lib/http/client.js

The rpc endpoint `/wallet/:id/passphrase` expects the new passphrase to be named `new` rather than `passphrase`.

client: use 'new' passphrase param

---

lib/http/rpc.js

`tree.matches` contains Buffers instead of hex strings, we need to return hexes. (also `revHex` accepts only string)

rpc: fix verifytxoutproof

---

bin/cli
lib/http/client.js
lib/http/wallet.js
lib/wallet/http.js

If a wallet was protected by a passphrase, the server would throw a 500 error and log "No Passphrase" even if one was passed via CLI. This passes it if it is passed as argument.

pass passphrase for key import

---

lib/http/rpc.js

Sign raw transaction should accept `vout` instead of `index`.

RPC: Create/Sign Raw Transaction fix

---

bin/cli

retoken wouldn't work for wallets that require a passphrase. Just needed to pass in the passphrase config from the CLI

pass the passphrase to retoken

---

lib/primitives/keyring.js

I was trying to create a multisig keyring outside of the walletdb and was losing the `witness` option. The options in `fromOptions` would get lost if the key was a buffer since it would return before the options were set.

pass options on keyring creation

---

lib/http/client.js
lib/http/wallet.js
lib/wallet/http.js

use req.wallet for lock coin endpoints

---

lib/http/client.js
lib/wallet/wallet.js

implement tux's fix for changing property name and more consistent behavior around setting passphrase on unencrypted wallet. 
Fixes #284 
Implements #300 by @tuxcanfly

More consistent behavior around setting passphrase on unencrypted wallet

---

lib/wallet/wallet.js

I don't see reason to block watchOnly wallets from funding transactions, there's another check in Sign which will throw error when signing.
So this PR removes watchOnly check in `wallet.fund/_fund`
`bmultisig` watchonly wallets or hardware wallets won't be able to fund/coinSelect transaction without this.
@chjj

Remove watchOnly check from wallet fund

---

lib/wallet/http.js

Makes it easier to distinguish between node HTTP server and wallet HTTP server in debug logs

Wallet: Minor log change

---

CHANGELOG.md

Could be expanded to include more example of configuration options that have changed. For example, some configuration options previously had `wallet-` prefixes that no longer need prefixes inside `wallet.conf` (`wallet-auth` is an exception).

CHANGELOG: Add section regarding wallet.conf

---

lib/primitives/mtx.js

The previously documented return value was {Boolean}, which remained by accident from when the function returned a success code: https://github.com/bcoin-org/bcoin/blob/9d90704b83763c05ce17afae3f940544b8c7ba0f/lib/primitives/mtx.js#L562

Correct scriptVector() return value to {Stack}

---

lib/node/fullnode.js

This PR correctly handles errors thrown by `broadcast()` in case a selfish node uses `sendTX()` and documents the return type of `sendTX()` (which is a `Promise`).

Fix full node sendTX() bug and omission

---

test/tx-test.js

This tests cover several methods:
* getAddresses - for outputs, inputs and both
* hashes - for outputs, inputs and both
* prevouts
* toNormalWriter - writer that should serialize data without witness
* isFree - check the priority of tx
* fee - roundFee and minFee
* getJSON - tests all params
What can be improved?
- `getModifiedSize` isn't used by getPriority anymore.
- More `valid` transactions - mostly witness transaction data is lacking (Spend from P2WSH and so on)
- More `invalid` transactions to cover more expected errors.

test-tx: add tx tests

---

docs/Configuration.md

There is a mismatch between the docs and what is in the code. Trying to start bcoin with `--network segnet4` results in an error.  Looking at the code here
- https://github.com/bcoin-org/bcoin/blob/v1.0.0-beta.15/lib/protocol/networks.js#L25
it shows 4 network types, `['main', 'testnet', 'regtest', 'simnet']`
This pull request reflects that in the documentation

docs: replace unsupported option with supported

---

lib/wallet/account.js

Accounts create methods can't use `createKey` without passing `Batch`.
I would like to leave methods for increasing depth without database update, but then you need to keep track of last updates, so on next `createKey` you can save all other keys as well. So decided to just fix it with this for now.

account: fix create methods

---

bin/spvnode

fixes fatal error trying to start with `bcoin --spv`
```
$ bcoin --spv
/home/ec2-user/bcoin/bin/spvnode:11
const node = SPVNode({
^
TypeError: Class constructor SPVNode cannot be invoked without 'new'
at Object.<anonymous> (/home/ec2-user/bcoin/bin/spvnode:11:14)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
```

fix SPV mode

---

lib/wallet/http.js

For OP_RETURN applications (like Publish Data plugin for bPanel) need to be able to pass `sort:false` to http wallet to maintain the order.

pass sort option through http

---

lib/primitives/txmeta.js
test/txmeta-test.js

Current behavior: the unconfirmed tx reports 505 confirmations, which is the current block height plus 2 (`chainheight - txheight + 1`) because `txheight` is `-1` when unconfirmed.
```
$ bwallet-cli send rb1qpymv5nnjcwngwpx93nvxm0wc7470nzu9rz2r99 0.01
{
"hash": "0babb01107d616b27e1831877558e369b00dffd7827fdcd624b7b21434869005",
"height": -1,
"block": null,
...
$ bcoin-cli tx 0babb01107d616b27e1831877558e369b00dffd7827fdcd624b7b21434869005
{
"hash": "0babb01107d616b27e1831877558e369b00dffd7827fdcd624b7b21434869005",
"witnessHash": "aec9b25b8f178ea4bd6b9811e02dbc775986a376b40986b85e1976ef6b25328c",
"fee": 2860,
"rate": 19861,
"mtime": 1526317134,
"height": -1,
...
"hex": "01000000000101c5a2e6171f2054b5c5f2a4e108136dbda11d89735e5918f88a04bc0846a762610000000000ffffffff0240420f00000000001600140 …
```

fix bcoin-cli tx "confirmations" return value when tx is unconfirmed (should be zero, currently isn't)

---

lib/net/pool.js
lib/wallet/wallet.js

Fix two typos in comments in `lib/wallet/wallet.js` and a wrong JSDoc return type in `lib/net/pool.js`.

Fix typos and JSDoc return type

---

package.json

Refs #500 
There are API incompatibilites with latest bcrypto i.e. `bcrypto@0.3.7`. Updated `package.json` to strictly use `0.3.2` for now.

pkg: update bcrypto

---

test/chain-test.js
test/node-test.js

This PR fixes an issue with CircleCI tests failing because of insufficient timeouts.

test: increase timeout for ci

---

test/pow-test.js

the test was randomly failing when `getProofTime` returns `-0`. Fixed by replacing `strictEqual` with `ok`.

test: fix get block proof equivalent time

---

lib/wallet/plugin.js

Refs #534 
The existing wallet plugin always reads `wallet.conf`, leading to test failures when a conf file with different `api-key` exists.
This PR extends the behavior of enabling a config file by passing `config: true` to the wallet plugin in addition to the node.

test: http-test - don't read wallet.conf

---

docs/Configuration.md

Had a few support chats about connecting to a remote bcoin server from a local client. Indicating here how to launch bcoin with node and wallet configs in one line. Also users might not realize that you can run bclient on its own locally, and the config files are still in the same place as bcoin itself.

Describes `wallet-` prefix for CLI config

---

lib/node/http.js

After b92839c82acd08f8d206e6c19d238192a1bb6cec# `Address.getHash` stopped accepting a string address,
which breaks some API calls (e.g. `/coin/address/:address`).
~Even though hash can be passed around as Buffer, address needs conversion to retrieve the hash. Therefore this PR restores string to address hash conversion in `getHash`.~
Instead of passing strings, I've updated the fix to pass `Address` from the `HTTP` layers. This is the correct fix because `chain.getCoinsByAddress` expects the input to be an Array of `Address`, rather than Array of `string` as was being passed earlier.

http: fix address/coins by address to use Address instead of string

---

lib/wallet/rpc.js

A test for this can be added to `rpc-test.js` in https://github.com/bcoin-org/bcoin/pull/550 once merged. I also have an unrelated work-in-progress test that uses this, and is how I found it.

wallet: get correct address for `getnewaddress` rpc

---

lib/bcoin.js

Trivial change to enable tab completion of API in a Node.js REPL.
Open a Node.js REPL, and:
```
const bcoin = require('.');
bcoin.<press-tab>
```
Will show the available API.

Tab completion of API in Node.js REPL

---

docs/Configuration.md

I got an `SyntaxError: Unexpected token -` error trying to instantiate a node with `log-level` today, other users might make the same mistake. This PR adds a table to the doc that illustrates the usage of hyphens and capital letters depending on how you pass the params over.

Docs: Describe different formatting for parameters (CLI, JS, config file, etc.)

---

lib/net/pool.js
test/node-test.js

This issue was uncovered by @OrfeasLitos in progress of writing [this guide](https://github.com/bcoin-org/bcoin-org.github.io/pull/107), in which an error is thrown when a peer requests a transaction from the inventory:
`[D:2018-08-27T19:15:36Z] (net) Error: item.hash is not a function (127.0.0.1:55362)`
The bug was introduced 20 days ago in https://github.com/bcoin-org/bcoin/commit/a0ac953079a5ce09eb23828239ed5ab70b975f0f and prevents all transaction broadcasting to peers!
Thanks to @tuxcanfly for finding the bug and checking for other occurrences (none found yet!)
Test is a little funny but it's the only way I could figure to hit that exact line.

Fixes pool.getBroadcasted() error item.hash is not a function

---

.circleci/config.yml

- Use cache only when installing
- Use workspaces to share node_modules

pkg: update ci

---

lib/wallet/http.js

HTTP Endpoint for creating transaction is also signing the transaction.
We have another endpoint /sign which can be used for signing.
* Makes tx sign optional /wallet/:id/create (true by default for backwards compatibility)

Allow optional signing in createTX

---

browser/index.html
browser/src/app.js
docs/Running-in-the-browser.md

Tiny fixes are needed to run bcoin in a browser.
The location of the `app.js` file gets confused in some browsers when running locally (Chrome kept trying to access `/app.js` as an absolute path `file:///app.js`)
Since the big refactor this year and use of bclient for RPC calls, the object returned from RPC calls is slightly different and was always being displayed as `null`.
An update to `blgr` is also required for bcoin-in-browser to work:
https://github.com/bcoin-org/blgr/pull/1, which re-adds the method `logger.format()` after it was refactored out a few months ago. This seems to be the cleanest way of restoring the in-page logger functionality.
These changes have been tested on local and a remote server, and functionality has been described in a new bcoin.io guide (pending merge): …

browser: update since refactor

---

.gitignore
docs/Beginner's-Guide.md
package-lock.json

Closes https://github.com/bcoin-org/bcoin/issues/619

pkg: add lockfile

---

docs/Configuration.md

Addresses confusion similar to https://github.com/bcoin-org/bcoin-docker/issues/8

docs/Configuration: SPV is command-line only

---

bin/node
bin/wallet

Looks like the docs have moved; this way users get directly sent to the updated URL.

update link to bcoin docs

---

bin/spvnode

To match behavior in `node` (fullnode) if a user wants to use `bmultisig` instead of the built-in wallet.

spvnode: parse --no-wallet flag

---

lib/mempool/mempool.js
test/mempool-test.js

Currently coinview does not account for spent coins in the mempool,
This does not create problems because we have additional checks in
right places which detect double spends, but technically
coinview should help you detect double spent in the mempool as well.
This way it will be compatible with chain.getCoinView.
getSpentView will still return all outputs that are available
in the mempool. (This could also return spentView from indexers if
available, this method is used by `signrawtransaction`.)

mempool: reflect spent coins in mempool coinview.

---

.eslintfiles
browser/src/app.js

This commit https://github.com/bcoin-org/bcoin/commit/0a71b445e0c12819e417bdf1df018fcb7bed4f0c removes `webpack` related files. The CI uses the the npm script `lint-ci`, which exits with a non zero code due to `eslint` looking for files that were removed from the project.
The commit message says that the files were removed temporarily, but the CI shouldn't fail temporarily. This commit removes the references to the files that no longer exist from `.eslintfiles` so that the CI can pass again.
description from: #678

Fix lint configs

---

lib/net/pool.js

As mentioned in #288 DNS discovery can be disabled when passing `--only`
The referenced issue also mentions `--nodes` when number of `--max-outbound` matches but I think that's an overkill. For instance, `btcd` disables DNS seeds only on `--connect`, not `--addpeer`.

pool: --only - disable dns seed discover

---

lib/node/http.js
lib/node/rpc.js
lib/wallet/http.js
lib/wallet/rpc.js

I dunno if this helpful for anyone else, but when playing with socket testing I noticed that both wallet and node http servers report some identical messages like `(http) Successful auth from 127.0.0.1.` but I wasn't sure which server I was hitting.
This PR simply changes the log context identifiers to `node-http` and `wallet-http` instead of just `http`

http: identify log messages as node-http and wallet-http

---

lib/mempool/mempool.js
test/mempool-test.js

Checks in verify in this block are related to `witness` malleability.
Discussion: https://github.com/bitcoin/bitcoin/issues/8279
> // SCRIPT_VERIFY_CLEANSTACK requires SCRIPT_VERIFY_WITNESS, so we
> // need to turn both off, and compare against just turning off CLEANSTACK
> // to see if the failure is specifically due to witness validation.
> -- Bitcoin Core reference https://github.com/bitcoin/bitcoin/blob/5039e4b61beb937bad33ac4300cc784642782589/src/validation.cpp#L906
Summary of the issue:
We may have received witness transaction from old node (without witness) or even with malleated witness, but we don't want to reject those transactions in the mempool. But we still want to detect non standard transactions, that are non-witness.
In case of witness transaction, `verifyResult` will fail …

fix malleability check in mempool

---

bin/bcoin-cli
bin/bwallet-cli
bin/cli
package.json

After installation, links `bcoin-cli` and `bwallet-cli` directly to bclient bin, already installed

pkg: link bclient to bin

---

lib/wallet/wallet.js
test/wallet-test.js

If you try to `wallet.send()` with an empty `outputs` array, the error you currently get is:
`No outputs available.`
This was confusing me because I thought the wallet was unable to find any coins to spend, like it had a zero balance or coinbase outputs were not mature yet.
This PR changes that error to `At least one output required.` which indicates to the user/developer more specifically which output is missing.

Wallet: better error for send() if no outputs given

---

CHANGELOG.md
lib/wallet/http.js
lib/wallet/wallet.js
test/http-test.js
test/wallet-test.js

Introduce `options.template` option to `createTX` wallet http call which will allow controlling if we want transaction templated.
By default `template` will be true and won't break current usage (checks if it was set and is not `false`).
If you don't want to sign transaction right away, it can be useful to store just plain transaction.
For some plugins this will be useful as well, e.g. PSBT which stores empty inputs.
Summary:
Other:
- Expose additional options to `createTX` http call. (`blocks`, `sort`)
- to have identical options for `send` and `createTX`.
- Add more option docs to createTX method.

Wallet option to skip templates.

---

lib/wallet/rpc.js
lib/wallet/txdb.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
test/rpc-test.js
test/util/assert.js

This PR merges: https://github.com/bcoin-org/bcoin/pull/526, https://github.com/bcoin-org/bcoin/pull/530, https://github.com/bcoin-org/bcoin/pull/531, https://github.com/bcoin-org/bcoin/pull/544, and https://github.com/bcoin-org/bcoin/pull/545.
Also added new test `rpc-test.js` that tests all of the above affected RPC calls, and a few others mainly to support those. Further RPC tests will be added in a different PR.

RPC: fix several wallet RPC calls and add RPC tests

---

CHANGELOG.md
lib/node/rpc.js
lib/wallet/rpc.js
test/http-test.js
test/node-test.js
test/wallet-rpc-test.js

Update the node rpc method `validateaddress` to match the latest bitcoind interface.
The new interface is defined here: https://bitcoincore.org/en/doc/0.17.0/rpc/util/validateaddress/
Add the wallet rpc method `getaddressinfo`
https://bitcoincore.org/en/doc/0.17.0/rpc/wallet/getaddressinfo/
Notably, the properties `ismine` and `iswatchonly` are moved to `getaddressinfo`,
which is a good thing because in bcoin, `validateaddress` had them
hardcoded to `false` anyways, and we know of an exchange that
was attempting to use the value `ismine` for integrations into their system.
`ismine` now properly returns the correct value for addresses that
fall into the lookahead
Tests are added for p2pkh, p2sh, p2wpkh and p2wsh. I don't love that I had
to add `undefined` keys to the `node-test.js` file, …

validateaddress and getaddressinfo RPC Update

---

lib/node/http.js
test/http-test.js

While writing docs for https://github.com/bcoin-org/bcoin-org.github.io/issues/139 and testing out all the socket hooks, I got a confusing error calling `rescan`:
```
Error: Cannot read property 'test' of undefined
```
Turns out (and will be well documented shortly...) that this call fails if the client has not already loaded a Bloom filter to the server. Other socket hooks already check for this, for example:
https://github.com/bcoin-org/bcoin/blob/01a71561b1677981a4b355f7deec46f50e68a855/lib/node/http.js#L616-L618
This PR also includes a test case that demonstrates another weird thing about this call (also soon to be well documented) which is that when the server matches a block to the filter, it sends a `'block rescan'` call _back_ to the client. If the hook is not in place, you get …

node-http: require Bloom filter is loaded for `rescan` socket call

---

package.json

This PR removes the webpack related scripts from the `package.json`. They are not very useful since the webpack configs were removed from the project.

npm scripts: delete webpack

---

CHANGELOG.md
browser/src/app.js
docs/configuration.md
etc/sample.conf
lib/blockchain/chain.js
lib/blockchain/chaindb.js
lib/node/fullnode.js

Closes https://github.com/bcoin-org/bcoin/issues/626 and https://github.com/bcoin-org/bcoin/issues/625
A few reasons why the coin cache should be removed:
- Performance actually decreases when the `coin-cache` setting increased, often times it's faster at a value of 0 (see discussion at https://github.com/bcoin-org/bcoin/pull/672).
- The JS heap is limited _(around 1.4GB)_, so the cache would be better _outside_ the JS heap, where the value can be raised to be larger without causing "heap out of memory" issues. LevelDB already does it's own caching, this can be adjusted with `cache-size` and that cache can be used to keep data in memory. Initial tests show that increasing `cache-size` doesn't have an effect on performance, so there could be other bottlenecks.
- A coin during sync is …

Remove coin cache

---

bench/hexstring.js
lib/utils/util.js

This PR is just a cleanup from the recent buffers-instead-of-strings switchover.
Although these methods do not get called rapidly (they're mainly for JSON responses and API calls)
@BluSyn was able to observe a performance improvement:
> ~50% faster when compared over 1000000 iterations
> difference is ~1300ms vs. ~600ms over 1m iterations

util: reverse buffers instead of strings

---

test/bech32-test.js

Adds additional information about the bech32 test vectors.
Updated to document both the valid and invalid test cases.
Pulled from https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

test: document bech32 test vectors

---

CHANGELOG.md
bench/blockstore.js
lib/bcoin.js
lib/blockchain/chain.js
lib/blockchain/chaindb.js
lib/blockchain/layout.js
lib/blockstore/README.md
lib/blockstore/abstract.js
lib/blockstore/common.js
lib/blockstore/file.js
lib/blockstore/index.js
lib/blockstore/layout.js
lib/blockstore/level.js
lib/blockstore/records.js
lib/node/fullnode.js
lib/node/node.js
migrate/chaindb4to5.js
test/blockstore-test.js
test/chain-test.js
test/mempool-test.js
test/pow-test.js
test/util/common.js

This adds a new module `blockstore` for storing blocks. It adds a file block store that has several advantages:
- Reduction of disk i/o when syncing the chain, this is due to reduction of database compaction (https://github.com/bcoin-org/bcoin/issues/585).
- Transaction data can be queried directly from block data, the `txindex` can point to this data instead of duplicating the tx data (https://github.com/bcoin-org/bcoin/issues/585).
- Ability to recovery from database corruption, as indexes are regenerated in the case that there are issues (https://github.com/bcoin-org/bcoin/issues/682).
- Bootstap a node from block data from other implementations, such as Bitcoin Core.
There can be multiple implementations of the blockstore interface, to give better flexibility to how data is stored. …

Add file block storage

---

lib/node/http.js

This commit simply adds an enforce line to check that the height being
requested to reset to is below the chain tip. This way we return a bad
request error rather than an internal server error.
Ported from https://github.com/handshake-org/hsd/pull/156

node-http: add check for height being below tip

---

.eslintfiles
docs/examples/client-api.js
docs/examples/create-sign-tx.js
docs/examples/wallet.js

Missed a few nits in the `docs/examples` merged in #699.
Adds that directory to the `.eslintfiles` to prevent recurrence.

linter: cover docs/examples

---

lib/blockchain/chain.js
test/chain-test.js

This has been patched in both bitcoind and btcd around February 20th, 2014. It was
shortly followed by a headers-first synchronization of blocks.
- https://github.com/bitcoin/bitcoin/commit/d8b4b49667f3eaf5ac16c218aaba2136ece907d8
- https://github.com/btcsuite/btcd/commit/50b6e10b5781772b0f6a506535f575d81a95dc7a

blockchain: do not accept forked chain older than last checkpoint

---

lib/blockstore/README.md

Fixes a minor mistake where the length of the block is mixed with the position of its last byte.

Replace 285 with 293 in blockstore README

---

lib/indexer/addrindexer.js
lib/mempool/addrindexer.js
lib/mempool/mempool.js

After discussing reviews with @braydonf, we found that we need to pass network to getPrefix even if it's used internally. If network is not passed getPrefix will use Network.primary which can change using `Network.set` or manually, so instead we will just use network from the node and mempool.
Changes:
- minor(bug): pass network to addr.getPrefix
- minor(style): return arrays and don't mutate txs array
- minor(perf): Don't allocate extra buffer

Indexer getPrefix

---

test/blockstore-test.js

promise.finally was introduce in node v10, so this test will fail on v8.6.0 node.
We support node from v8.6.0 (will update engine in different PR, currently doing tests on that topic),
so this fixes that minor issue in test.

blockstore-test: use try/catch instead of promise.catch/finally.

---

lib/net/packets.js
lib/net/peer.js
test/net-test.js

Starts tests for the net module, and will be expanded with additional PRs.
cc: @tuxcanfly and @pinheadmz

Add net tests

---

lib/indexer/indexer.js
test/indexer-test.js

This fix is for a pretty obscure edge case that I ran into when building out a custom indexer but found it did affect the built-in indexers as well so thought it might be worth integrating as a fix. 
The problem comes up when you close a node with indexers, re-open it after other blocks on the network have been added, and then resync. What happens is that the indexer can have multiple listeners for when a block comes in. To the indexer, this looks like duplicate blocks have come in and it will remove a block. This will then cause `rollforward` to be called on a subsequent block as it continues to sync. In the case of my custom indexer, there was some side behavior that was causing `rollforward` to fail in this particular case on the resync and so after the block gets removed, the indexer …

add ability to track listeners and remove them on close for indexer

---

docs/configuration.md

It is actually `8`, not `30`:
https://github.com/bcoin-org/bcoin/blob/0551096c0a0dae4ad8fb9f1e135b743d50a19983/lib/net/pool.js#L3531

docs: update max-inbound default

---

lib/node/http.js
test/http-test.js

Add an HTTP endpoint to the Node for fetching block headers.
- `GET /header/:block`
This endpoint makes 1 less database call than fetching a block by hash or height. The `view` is not necessary for `header.getJSON`.
It also returns far less data and should always be consistent with the amount of data that it returns.

node/http: get block header by hash/height

---

lib/wallet/txdb.js

Solves a rare race condition between block processing and spending.
**Error:**
Assertion failure @ bcoin/lib/wallet/txdb.js:1618
Stack trace with `--async-stack-traces`:
```
AssertionError [ERR_ASSERTION]: Assertion failed.
at TXDB.getAccountCredits (bcoin/bcoin/lib/wallet/txdb.js:1620:7)
at async TXDB.getCoins (bcoin/bcoin/lib/wallet/txdb.js:1667:21)
at async Wallet._fund (bcoin/bcoin/lib/wallet/wallet.js:1119:15)
at async Wallet.fund (bcoin/bcoin/lib/wallet/wallet.js:1088:14)
at async Wallet.createTX (bcoin/bcoin/lib/wallet/wallet.js:1273:5)
at async Wallet._send (bcoin/bcoin/lib/wallet/wallet.js:1327:17)
at async Wallet.send (bcoin/bcoin/lib/wallet/wallet.js:1312:14)
```
Issue triggered by call to `getAccountCredits`:
Calls `getAccountOutpoints` (txdb `layout.C` w/ bucket.keys) returns …

txdb: Ignore coin if it suddenly doesn't exist

---

docs/getting-started.md

With a minimal installation some of these packages may not already be included, nor would it be obvious based on the error messages which packages need to be installed.

docs: debian/ubuntu build dependencies

---

package.json

The CHANGELOG is already labeled as version `2.0.0-dev`. This distinction gets more and more important as github master branch diverges from the 1.0.2 release on npm. Support requests will go much faster since `bcoin-cli info` will return a different version if installed from npm vs github.

pkg: bump version to 2.0.0-dev

---

docs/examples/connect-to-the-p2p-network.js
docs/examples/create-a-blockchain-and-mempool.js
docs/examples/get-tx-from-chain.js
docs/examples/spv-sync-wallet.js
lib/blockstore/index.js

While here, fix docs examples which were failing due to improperly configured `blockstore`.
Also a minor nit: `new bcoin.Chain()` instantiates a new `Chain` without a `blockstore`, since `options` is `null`. This is because we only validate `options` if they are given, but if given we require a `blockstore` (except in spv). We could add another check if `options` is `null`. Thoughts?

blockstore: skip location for memory store

---

bin/bcoin-cli
bin/bwallet-cli
docs/cli.md
docs/configuration.md
docs/examples/client-api.js
docs/getting-started.md
lib/bcoin-browser.js
lib/bcoin.js
lib/client/index.js
lib/client/node.js
lib/client/wallet.js
lib/wallet/client.js
package-lock.json
package.json
test/http-test.js
test/indexer-test.js
test/node-rpc-test.js
test/wallet-rpc-test.js

Closes https://github.com/bcoin-org/bcoin/issues/834

Create client module from bclient

---

lib/wallet/txdb.js
test/wallet-test.js

Closes #821 
Although issue #821 and similar issues can be abated by using a larger BIP44 `lookahead` value and adjusting the timing of bloom filter updates (patch in progress) there still exists an edge case in `txdb` which can be problematic even after these issues are solved. This PR tests a more acute version of this edge case like so:
- A transaction (`tx1`) is broadcast with outputs to these two addresses:
1. An address from Alice's wallet `A`
2. An address derived from some externally derived key `B`.
- `tx1` confirms, and Alice's wallet balance correctly reflects only the coin sent to key `A`
- Alice imports the private key `B` into the same wallet, and rescans.
Outcome: Alice's wallet shows `tx1` as UNCONFIRMED, with unexpected values for both confirmed and unconfirmed balance. …

Create txdb credit for known key paths when confirming

---

bin/bcoin-cli
lib/client/node.js
test/http-test.js

- Adds `getBlockHeader` method to the `NodeClient`
- Adds `header` method to `bcoin-cli`
- Updates tests to use `getBlockHeader` over `get('/header')`
Port of https://github.com/bcoin-org/bclient/pull/21/

Client block header

---

lib/mining/miner.js
lib/mining/template.js
lib/net/common.js
lib/net/hostlist.js

Use `bcrypto` as a source of randomness over `Math.random`.
This is based on work by chjj on hsd. 
See https://github.com/handshake-org/hsd/commit/f36670bd5d12b69bf53a7351da5dd1f77986e0d4
Addresses https://github.com/handshake-org/hsd/issues/107

bcoin: use cryptographic randomness

---

lib/node/http.js

Return the number of orphans in the mempool for `GET /` on the Node HTTP server. I found this to be an interesting number to watch.

node/http: get info mempool orphan count

---

lib/workers/worker.js

This will give worker processes the title 'bcoin-worker' instead of the more generic 'node'.

Add title to worker processes

---

bin/bwallet-cli
lib/client/wallet.js

Useful to release coins to be spent that are used in a transaction that is problematic to broadcast because of policy conflicts.

Add abandon tx to CLI and client

---

lib/wallet/txdb.js
lib/wallet/wallet.js
test/wallet-test.js

Recently a rogue node on Handshake generated a chain of over 10,000 transactions from a single coin, each spending the change output of its parent. Mempool relay policy limits these chains at 25, but the wallet will keep generating and trying to broadcast. Transactions were evicted from the mempool, turning it into at least one chain of orphans. The node kept rebroadcasting after receving each block, and it was a mess!
This PR prevents the wallet from exceeding the limit on unspent tx chains.

wallet: prevent chains of unconfirmed spends exceeding policy limit

---

lib/blockstore/abstract.js
lib/blockstore/common.js
lib/blockstore/file.js
lib/blockstore/level.js
lib/indexer/filterindexer.js
test/blockstore-test.js

This adds the ability to persist merkle blocks to disk for cases when the transactions have not yet been sent to the wallet. This is in the case of chain reorganizations, the wallet running as a separate process, and in other cases where blocks may be downloaded but not yet added to the chain.

Add merkle block data type and methods

---

bin/bwallet-cli

I'm not sure how this worked before, or if it was affected by https://github.com/bcoin-org/bcoin/pull/444
Consider this process:
- Create a watch-only multisig wallet, import xpubs, get receive address, receive coins.
- Create TX with https://bcoin.io/api-docs/#create-a-transaction
Currently throws: `Error: Cannot sign from a watch-only wallet.`
After merge `mktx` can be called with `--sign=false` which will bypass `wallet.sign()` and return a TX template.
Finally:
- Sign TX with https://bcoin.io/api-docs/#sign-transaction
I'm working on the examples right now for api-docs, and it will be added shortly to https://github.com/bcoin-org/bcoin-org.github.io/pull/161

bwallet-cli: add sign parameter

---

lib/wallet/rpc.js

Another mysterious change since the last time I ran through every command in the API docs.
command: `bwallet-cli --network=regtest rpc dumpwallet $path`
Notice how the dump is being generated by a regtest wallet, and the private keys in WIF format have regtest prefixes, but the base58 addresses are all mainnet.
Current:
```
cNUUoZYmUGoJyodrNaohzfu6LmKy7pBk6yqubJcTeL5WPWw97DQ1 2019-10-22T18:26:58Z label= addr=1Z79Rwb6Zw9JoNqt45ewZf5D51GSTwkjY
cNH7YBw6haTB3yWkAndoPhwXRLNibXjWAYpqRQdvqPKLeW7JAj6h 2019-10-22T18:26:58Z change=1 addr=12D7WDNd7Ari9qacWsZvVUYCebBFk1zuhF
cNmBeL4kpjLtNZcvjSezftq4ks6ajzZRi1z2AGpuBGy6XjxzytiQ 2019-10-22T18:26:58Z label= addr=1314fEWLTyVo51nBeWd6vrDQ6HnXLFBRxA
...
```
After merge:
```
cNUUoZYmUGoJyodrNaohzfu6LmKy7pBk6yqubJcTeL5WPWw97DQ1 2019-10-22T18:29:15Z label= …
```

wallet-rpc: dump wallet backup with correct network

---

bin/node
bin/spvnode

This addresses user concern https://github.com/bcoin-org/bcoin/issues/572
and replaces https://github.com/bcoin-org/bcrypto/pull/9
Test by moving or renaming the `build` directory in `bcrypto` which will force bcrypto to use nodejs crypto or proprietary crypto scripts for everything.
This PR throws an Error during `handleOpen()` that the bindings could not be found unless user explicitly sets `NODE_BACKEND=js` or `NODE_BACKEND=node`

Quit if native bcrypto bindings are missing

---

lib/node/rpc.js
lib/utils/message.js
lib/wallet/rpc.js
test/node-rpc-test.js
test/utils-test.js
test/wallet-rpc-test.js

Builds on top #464, fixes issue #460 
General updates on the `signmessagewithprivkey`, `verifymessage` and
`signmessage` :  
These two calls are outdated and only work for old `P2PKH` addresses. It can
not be used with witness transactions or p2sh.  
BitcoinCore thread about this: [Bitcoin Core issue][core-signmessage]  
Trezor implemeneted variation of signmessage, details in [the issue][trezor].
There's new proposal for generic signed messages signing:
[BIP 322: Generic Signed Message Format][bip322] and [BIP 322 - PR][bip322-pr].
There's also an [discussion][core-rpcutils] about not adding new utility
RPC calls to the RPC that can be implemented as a library.
Other updates:
- organize utils tests
- add TODO for util tests to move to their respective repositories
- encoding tests should …

RPC signmessage

---

lib/utils/index.js

Sorry, I should've caught this while reviewing #802.
I'd like to use the message signing utilities in https://github.com/pinheadmz/bid, where I had to re-write / copypaste them until #802 merged.

bcoin: expose utils/message

---

CHANGELOG.md
bin/bcoin-cli
lib/client/node.js
lib/node/http.js
lib/wallet/nodeclient.js
lib/wallet/nullclient.js
lib/wallet/walletdb.js

While I was updating the api-docs this morning I noticed that the request `/fee` was listed but had no description or examples. While this endpoint does exist in the HTTP API, it was never exposed in the CLI.
In addition, `NodeClient` was written to use a socket call to get the fee estimate. This is fine, but would also require an extra step for client (`open()` which would include `auth()`, before a socket call is possible). I'm not sure the history here, but it should be okay to just `GET` the fee like any other HTTP API request.

bcoin-cli: expose estimateFee

---

lib/wallet/wallet.js

A user on slack got this error because they assumed the default value for `zap()` was 72 hours:
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value: assert((age >>> 0) === age)
at TXDB.zap (/usr/app/node_modules/bcoin/lib/wallet/txdb.js:2007:5)
at Wallet._zap (/usr/app/node_modules/bcoin/lib/wallet/wallet.js:1905:22)
```

jsdocs: no default value for wallet.zap()

---

lib/node/rpc.js
test/node-rpc-test.js

Fixes the `confirmation` field in both `getblock` and `getblockheader`. It is supposed to return `-1` if the block is not in the main chain. This allows applications to be able to determine if blocks are in the main chain or not.
Also adds properties to the `getblock` RPC verbose output that are in `bitcoind` but not `bcoin`. These include:
- `nonce`
- `nTx`
I also added the property `nonce` to `getblockheader` verbose output but skipped `nTx` for now because that would involve a bigger change. If that is something that people would also like as part of this PR, would be happy to add it.
Includes tests for the RPC `getblock`.
Closes https://github.com/bcoin-org/bcoin/issues/918

rpc: getblock fix

---

CHANGELOG.md
lib/node/rpc.js
test/node-rpc-test.js

Follow-up of https://github.com/bcoin-org/bcoin/pull/919

Bits in hex for rpc block methods

---

lib/bcoin-browser.js

Fixes a bug that was introduced in #838 which breaks browser builds of bcoin. Since the browser bcoin doesn't have `define`, an error is thrown: `TypeError: bcoin.define is not a function`. This PR uses the same module loading approach as the other modules in this file.

browser: fix client module loading

---

docs/configuration.md
lib/wallet/node.js
lib/wallet/plugin.js
lib/wallet/walletdb.js

The behavior of checkpoints in the wallet will skip transactions before the last checkpoint. This is likely an optimization for wallets that do not have transactions before the last checkpoint. In the case that there are transactions before they would be skipped. This type of optimization can be later added to instead use the known date the wallet was generated.
This is a follow-up PR to https://github.com/bcoin-org/bcoin/pull/931.

wallet: remove checkpoints that skip transactions

---

node_modules/bsocks/lib/socks.js
node_modules/bsocks/package.json
package.json

See https://github.com/bcoin-org/bsocks/pull/1
Closes https://github.com/bcoin-org/bcoin/issues/206

Fix proxy support

---

test/http-test.js

Closes https://github.com/bcoin-org/bcoin/issues/957
(hopefully)
See https://github.com/bcoin-org/bcoin-org.github.io/pull/159
Amazingly, the errant bloom filter in this test was apparently false-positive enough to pass _most_ of the time.

test: fix http-test for rescanning with bloom filter

---

lib/wallet/rpc.js
lib/wallet/walletdb.js
test/wallet-rpc-test.js

Tested manually using these steps, checking the balance along the way via `bwallet-cli balance`:
1. Starting a regtest node via `bcoin --network=regtest`.
2. Getting address from the wallet using `bwallet-cli address default`.
3. Mining blocks with `bcoin-cli rpc generatetoaddress <blocks> <address>`.
4. Getting another address and then sending funds to that address via `bwallet send <address> <value>`.
5. Mining a block.
6. Removing the tx from the wallet via `bwallet-cli removeprunedfunds <tx-hash>`.
7. Getting a txoutproof for the tx via `bcoin-cli rpc gettxoutproof '["<tx-hash>"]' <block-hash>`.
8. Importing the tx via `bwallet-cli rpc importprunedfunds <rawtx> <txoutproof>`.

Fix wallet rpc method to import tx

---

lib/wallet/rpc.js
test/wallet-rpc-test.js

Closes https://github.com/bcoin-org/bcoin/issues/1015
Users are getting the error `"Cannot read property 'equals' of null"` when generating blocks to their wallet in regtest. The error is due to failed attempts to decode an output script address when none exist (like the OPRETURN witness commitment of a coinbase TX)

wallet-rpc: getreceviedbyaddress should ignore non-address outputs

---

lib/wallet/walletdb.js
test/http-test.js
test/node-http-test.js
test/node-test.js
test/wallet-http-test.js
test/wallet-test.js

Simple change to the default value in `WalletDB` so all newly created wallets generate segregated witness addresses. Had to update several tests to comply.

Wallet: Use SegWit by default

---

lib/blockchain/chain.js
lib/blockchain/chainentry.js

Resolves #1028  
- As miners are using OvertAsic boost to produce blocks with random version numbers, which adds more false positives to the [BIP91](https://github.com/bitcoin/bips/blob/master/bip-0091.mediawiki) signalling. 
- This removes the warning which is haunting users for a long time.

removed [warning] (chain) unknown version bits in block

---

lib/hd/mnemonic.js
test/hd-test.js

This commit changes the mnemonics length to 256 bits to get 24 seed phrases instead of 12 previously being used by bcoin-wallet. Also, this closes the previously opened draft PR #1060.

256 bit mnemonic update

---

lib/primitives/coin.js
lib/primitives/mtx.js
lib/wallet/wallet.js
test/wallet-test.js

This PR is based on [this](https://github.com/bcoin-org/bcoin/pull/858)
The idea is to calculate the `effectiveValue` of a coin for a new coin selection algorithm.
EffectiveValue = IntrinsicValue - Cost of Spending this coin
To calculate the `effectiveValue` of a coin, we need to estimate its accurate size, `estimateSpendingSize()` is used for that.
Since the output size is fixed, we can calculate the total required input value (total amount to be spent + fee based on the size of outputs). To calculate the fee based on output size, we need to calculate the size of tx without inputs. `estimateSizeWithoutInputs()` is used to calculate that.

Added functions `estimateSpendingSize()` and `estimateSizeWithoutInputs()` for better tx size estimation

---

lib/net/peer.js
test/net-test.js
test/p2p-test.js

- Implemented unit and peer-to-peer tests to witness compact blocks `bandwidth switching` between 2 bcoin nodes.
- Updated `compactBlocks` implementation to support compact block relay with witnesses by default (v2).

Compact blocks tests: Switching bandwidth modes

---

CHANGELOG.md
lib/blockchain/chaindb.js
lib/blockstore/common.js
lib/blockstore/file.js
lib/blockstore/level.js
lib/golomb/golomb.js
lib/indexer/filterindexer.js
lib/indexer/index.js
lib/indexer/indexer.js
lib/node/fullnode.js
lib/node/node.js
lib/node/rpc.js
lib/primitives/block.js
migrate/indexerdb0to1.js
migrate/latest
test/block-test.js
test/filter-test.js
test/node-rpc-test.js

- Adds support for filter types referenced in [BIP158](https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki) & [BIP157](https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki)
- Fixes the getblockfilter RPC message. Previously the RPC message implemented had the form 
`getblockfilter "hash"`
however as per [Bitcoin core docs](https://bitcoincore.org/en/doc/0.19.0/rpc/blockchain/getblockfilter/), the RPC message is supposed to be
`getblockfilter "hash" ( "type" )`
where the `type` by default is BASIC.

Add support for BIP158 filter types.

---

test/node-rpc-test.js

This PR fixes the `getnettotals with peer` test in `node-rpc-test.js` . 
The test previously failed when ran in an environment where the access to any external DNS was not available(There was a size mismatch due to addr packet not being sent).

Fixed getnettotals test

---

test/taproot-check-test.js

witness with one stack element should just be a signature (key path spend, not script path)
and since the signature is empty.

test: covers 'SCHNORR_SIG_SIZE'

---

lib/blockchain/chain.js
lib/blockchain/chaindb.js
lib/client/node.js
lib/node/http.js
lib/wallet/client.js
lib/wallet/http.js
lib/wallet/nodeclient.js
lib/wallet/nullclient.js
lib/wallet/rpc.js
lib/wallet/walletdb.js
test/wallet-rpc-test.js

- `rescan` make wallets rolled back to the specified height and check the blockchain for transactions containing specified address hashes. 
- `abortrescan` allows users to stop rescanning process triggered by the `rescan` RPC command.

[wallet-RPC] Add and Cover test rescan abortrescan RPC commands

---

CHANGELOG.md
bench/txdb.js
lib/wallet/layout.js
lib/wallet/txdb.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
migrate/latest
migrate/walletdb7to8.js
test/wallet-test.js

The `u` bucket will only store the following:
1. Coins that have not been included in any transaction (used as inputs)
2. Outputs of confirmed transactions (we are absolutely sure that these coins are spendable)
3. Outputs of unconfirmed transactions (in case of a `zap` we will remove these from `u`)

feat: created a new bucket `u` to store only spendable credits

---

package.json
test/coinselector-test.js

- added `BCOIN_RUN_LONG_TESTS` to `package.json` which defaults to `true` when running `npm run test-ci`
- modified wallet integration tests to run only on CI
To run integration tests locally, you can run `export BCOIN_RUN_LONG_TESTS=true` before running the tests.
If a test needs to be only run on CI in the future then we can use:
```js
if (!process.env.BCOIN_RUN_LONG_TESTS)
this.skip();
```

Integration tests will not run by default locally but will run on CI

---

migrate/indexerdb0to1.js
migrate/latest

migrate: bump up the spvchain database version in filter indexer migration

---

lib/node/http.js
test/filter-test.js
test/indexer-test.js
test/node-http-test.js

Since the filter indexers have been refactored, we missed one affected module: the http info response.
Tests are a bit spread out, but cover 0, 1 and 2 filter indexers.
`bcoin-cli info`
OLD:
```
"indexes": {
"addr": {
"enabled": true,
"height": 221063
},
"tx": {
"enabled": true,
"height": 243394
},
"filter": {
"enabled": false,
"height": 0
}
},
```
NEW:
```
"indexes": {
"addr": {
"enabled": true,
"height": 222851
},
"tx": {
"enabled": true,
"height": 245461
},
"filter": {
"BASIC": {
"enabled": true,
"height": 189074
}
}
},
```

http: fix getinfo from updated filter indexers

---

lib/primitives/address.js
lib/primitives/tx.js
test/mtx-test.js
test/node-rpc-test.js
test/node-test.js
test/wallet-rpc-test.js

Closes #521 
Closes #629 
I'm not sure what the purpose of this check is, and I'm working on a project where a 0-input transaction is fed into Bitcoin Core's `fundrawtransaction` for inputs.

tx: allow 0-input serialization

---

lib/blockchain/chain.js
test/chain-progress-test.js

As discussed in #1110 , there was a problem with the sync progress for SPV nodes. This PR readds the old algorithm just for SPV nodes.

Fix: readd old algorithm to fix progress for SPV nodes

---

bin/bcoin-cli
bin/bwallet-cli

Fixes #967 .
Made changes as proposed in the solution, suggested in the issue.

Fix: Added timeout configuration to NodeClient, both bwallet-cli and bcoin-cli

---

lib/hd/hd.js

Fixes #1122 
This patch fixes the issue described by changing the parameter types according the corresponding method called, as suggested in the issue solution.

Fix: Type mismatch between return types and options in HD.js and private.js

---

lib/bcoin.js
lib/descriptor/abstractdescriptor.js
lib/descriptor/common.js
lib/descriptor/index.js
lib/descriptor/keyprovider.js
lib/descriptor/parser.js
lib/descriptor/type/addr.js
lib/descriptor/type/combo.js
lib/descriptor/type/multisig.js
lib/descriptor/type/pk.js
lib/descriptor/type/pkh.js
lib/descriptor/type/raw.js
lib/descriptor/type/sh.js
lib/descriptor/type/wpkh.js
lib/descriptor/type/wsh.js
lib/hd/common.js
lib/hd/hd.js
lib/hd/keyorigininfo.js
lib/node/rpc.js
test/data/descriptors/COPYING
test/data/descriptors/desc-invalid.json
test/data/descriptors/desc-privatekeys.json
test/data/descriptors/desc-valid.json
test/descriptor-test.js
test/keyorigininfo-test.js
test/keyprovider-test.js
test/node-rpc-test.js

This pr implements [getdescriptorinfo](https://developer.bitcoin.org/reference/rpc/getdescriptorinfo.html) rpc by adding a descriptor module.
If the argument string of getdescriptorinfo() rpc is a valid string it is parsed into a **_AbstractDescriptor_** object. 
Along with that various parts of the string, such as origin information, keys (Public/Private), and derivation path (along with **hardened** or **unhardened** information)  are parsed into **_PubKeyProvider_** object respectively. If the descriiptor string contains a checksum it will be validiated and if a checksum is not present we will calculate one. 
**Note: The input descriptor string doesn't require checksum to be present**.
The **AbstractDescriptor** class has **_PKDescriptor_**, **_PKHDescriptor_**, **_WPKHDescriptor_**, …

Adds descriptor module with getdescriptorinfo rpc

---

lib/btc/amount.js
lib/btc/uri.js
lib/primitives/coin.js
lib/primitives/output.js

`Number.isSafeInteger` is only true when int54.
Because here also checks whether positive, it's actually uint53 which can pass these assertions.
both int64 and uint64 wrong and misleading

fix: neither uint64 or int64 safe integer

---

lib/descriptor/abstractdescriptor.js
lib/descriptor/keyprovider.js
lib/descriptor/type/addr.js
lib/descriptor/type/combo.js
lib/descriptor/type/multisig.js
lib/descriptor/type/pk.js
lib/descriptor/type/pkh.js
lib/descriptor/type/raw.js
lib/descriptor/type/sh.js
lib/descriptor/type/wpkh.js
lib/descriptor/type/wsh.js
lib/node/rpc.js
lib/script/script.js
lib/wallet/account.js
test/data/descriptors/desc-addresses.json
test/descriptor-test.js
test/node-rpc-test.js
test/script-test.js
test/wallet-test.js

This pr implements deriveaddresses rpc.

Adds deriveaddresses rpc
