bcoin-org/bcoin

- .dockerignore
- .gitignore
- Dockerfile
- docker-compose.yml
Minimal docker configuration using alpine linux.
Easy to start node with just: `docker-compose up -d`
Defaults to segnet4
Set network type and ports in docker-compose.yml
Allows you to easily run multiple networks on same server (eg, run both segnet4 and testnet)
> Add docker configs

- lib/net/pool.js
Fix multiple BroadcastItem.prototype.reject definition
> pool: fix BroadcastItem multiple reject methods

- browser/index.html
Minor formatting.
URL to the bcoin repo should be in a new tab since the user could be syncing.
> formatting and url target

- docs/REST-RPC-API.md
Some of the paths were changed. Updated all paths based on http servers.
> [WIP] Fix REST-RPC-API docs

- lib/wallet/rpc.js
Compatibility to Bitcoin Core RPC.
Issue #262.
> RPC: change default to getbalance

- lib/http/server.js
In recent PR #325 there was no confirmation variable declared.
> Fix confirmations not found

- lib/protocol/networks.js
> networks: update simnet bech32 prefix

- lib/wallet/http.js
Will provide additional info, if key was added to database or it was duplicate.
Same for removal
> Shared key updates

- lib/wallet/wallet.js
- test/wallet-test.js
> wdb: fix hasAccount

- bin/wallet
- package.json
Fixes: `./bin/wallet`.
Adds: `bcoin-wallet` binary for `npm install`.
> Fix wallet bin

- docs/Beginner's-Guide.md
Updating the minimum node.js version to match the minimum version specified in package.json.
> Updating min node version in docs

- test/tx-test.js
pr that got merged was written before wallet-rewrite.
Updating BufferWriter dep.
> Test: Update bufferWriter 

- docs/Examples/client-api.js
- docs/Examples/connect-to-peer.js
- docs/Examples/connect-to-the-p2p-network.js
- docs/Examples/create-a-blockchain-and-mempool.js
- docs/Examples/create-sign-tx.js
- docs/Examples/fullnode-and-wallet.js
- docs/Examples/fullnode.js
- docs/Examples/get-tx-from-chain.js
- docs/Examples/miner-configs.js
- docs/Examples/peers-plugin.js
- docs/Examples/spv-sync-wallet.js
- docs/Examples/wallet.js
Updated examples as per the latest changes to master.
> docs: updated examples

- lib/primitives/mtx.js
- test/tx-test.js
This will recover View from the coins of each input.
This is really handy if you want to pass MTX to client and client wants to use it for signing.
> MTX - Recover view from JSON

- lib/wallet/account.js
- test/wallet-test.js
> account: fix change derivation path

- lib/wallet/node.js
Fix config variables in wallet/node.
> Wallet node configs

- lib/net/pool.js
- lib/wallet/wallet.js
> wallet: fixed typos; pool: minor jsdoc (#511)

- test/pow-test.js
Tests for difficulty adjustments. Ported from bcash, in turn referring to core's `pow_tests.cpp`
> test: add pow-tests

- test/txmeta-test.js
Fixes https://github.com/bcoin-org/bcoin/issues/515
-- Sorry! 😬 @tuxcanfly
> test/txmeta: fix lint

- test/node-test.js
Should use a concrete function for increasing timeout.
> test: fix timeout for node test

- lib/blockchain/chaindb.js
- lib/mempool/fees.js
- lib/net/peer.js
- lib/wallet/txdb.js
- lib/wallet/walletdb.js
Minor: fixes lint issues on master.
> multi: fix lint warnings

- webpack.app.js
- webpack.browser.js
> remove bcrypto/compat

- webpack.compat.js
Sorry, missed a webpack config file.
> remove bcrypto/compat from compat webpack

- lib/net/pool.js
> pool: watchAddress continue to accept addr string

- bin/spvnode
Addresses #608 and extends #563
> spvnode: add new option `file` instead of config

- lib/pkg.js
Added more info to pkg.js file as in the [hsd equivalent](https://github.com/handshake-org/hsd/blob/4b04d9a2f9094b9c4c8e17346e7f24517f0a0336/lib/pkg.js).
Also import name and version from `package.json` so these stay up to date with the package information.
> add currency and other info to pkg

- lib/primitives/keyring.js
- test/keyring-test.js
The implemented function returns the ith key of the provided multisig script and throws if the parameters are incorrect. The relevant static method and a test are provided as well.
> Implement and test KeyRing.fromMultisigScript(script, i)

- lib/net/pool.js
- lib/primitives/address.js
- lib/wallet/http.js
Minor fixes
Related PRs: #581, #612
> address minor fixes

- bench/buffer.js
- bench/chacha.js
- bench/coins.js
- bench/merkle.js
- bench/tx.js
- bench/walletdb.js
The dependencies have changed that are being used in the benchmark tests, these are the necessary fixes for all the benchmark files. Fixes from https://github.com/bcoin-org/bcoin/pull/451
> bench: update and fix api and dependencies

- test/http-test.js
- test/node-test.js
Closes: https://github.com/bcoin-org/bcoin/issues/717
> test: avoid port collision with a running regtest node

- lib/blockchain/chain.js
- test/chain-test.js
This matches the error code returned by bitcoind.
> chain: add fee overflow test; rename error

- lib/indexer/indexer.js
- lib/indexer/txindexer.js
> move hasRaw check to txindexer

- SECURITY.md
Add JJ's keybase key. See #849 and #799 for discussion
> security.md: add jj keybase key

- bin/bcoin-cli
- lib/client/node.js
- Adds a `getFilter` method to the `NodeClient`
- Exposes it via the CLI
> Client and CLI Filter Command

- test/blockstore-test.js
- test/util/common.js
> test: fix blockstore paths for windows

- docs/getting-started.md
- package.json
- snap/snapcraft.yaml
Updates Getting Started guide in docs, package.json, and the snap file.
Anyone running Ubuntu with snapd? Would appreciate a check on that.
I'm looking around but I don't think we need to update https://github.com/bcoin-org/bcoin-docker, maybe some of the installation guides in https://github.com/bcoin-org/bcoin-org.github.io though.
> Require nodejs v10 minimum

- lib/wallet/walletdb.js
- test/wallet-test.js
Closes https://github.com/bcoin-org/bcoin/issues/930
> wallet: set tip after txs have been added

- lib/node/spvnode.js
- lib/wallet/nodeclient.js
- test/wallet-test.js
> Prevent out-of-memory crash during sync with wallet as plugin

- lib/indexer/indexer.js
Closes https://github.com/bcoin-org/bcoin/issues/794
> lib: gracefully close indexer when stopping

- lib/wallet/http.js
- lib/wallet/walletdb.js
- test/wallet-test.js
Closes https://github.com/bcoin-org/bcoin/issues/938
> Use correct confirmation count for "confirmed" and "tx" events

- node_modules/bdb/package.json
- node_modules/bdb/src/binding.cc
- node_modules/bdb/src/napi-macros.h
- package.json
See https://github.com/bcoin-org/bdb/pull/8 and https://github.com/bcoin-org/bdb/pull/7 for details.
> Fix several segmentation faults with leveldb bindings

- etc/sample.wallet.conf
Closes https://github.com/bcoin-org/bcoin/issues/947
> docs: remove wallet checkpoint option

- bin/node
- bin/spvnode
see:
https://github.com/bcoin-org/bcrypto/commit/0ff4ad6f969aa8690258c9aeee29aab4f1726d27
and:
https://github.com/handshake-org/hsd/commit/ded61308682d7d0b4bafe6c4e8c6880fc20f1660
> bin: remove unneeded bcrypto backend warning 

- lib/wallet/masterkey.js
- test/wallet-http-test.js
> Wallet: enable seed phrase recovery from API

- test/node-rpc-test.js
- `getconnectioncount`
- `getpeerinfo`
-  `getchaintips`
-  `getblockhash`
- `getblock`
> Node RPC test

- test/wallet-http-test.js
1. list wallets: primary and test
2. change passphrase: locked wallet should be unlocked only by the correct passphrase
> Test coverage

- SECURITY.md
- Add @nodech to the security keys.
> pkg: update security.md

- test/node-rpc-test.js
Added node RPC test for `getnettotals`
> Added node RPC test

- lib/golomb/basicFilter.js
- lib/golomb/golomb.js
- lib/primitives/block.js
- test/gcs-test.js
This PR creates a new class BasicFilter which inherits the class golomb and makes it more modular by replacing the hardcoded values of p and m.
> added the basicFilter class

- lib/net/common.js
- lib/net/framer.js
- lib/net/packets.js
- lib/net/parser.js
- lib/net/peer.js
- lib/net/pool.js
- lib/node/fullnode.js
- test/indexer-test.js
- test/net-test.js
- test/p2p-test.js
This PR implements the getCFHeaders in BIP157 as required by issue #943.  [BIP 157](https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki#Filter_Types)
> Feat: added support for BIP157
